# Generated by Django 3.0.8 on 2020-07-30 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('slug', models.SlugField(blank=True, verbose_name='slug')),
                ('ph', models.DecimalField(decimal_places=1, max_digits=2, verbose_name='soil pH')),
                ('speed', models.IntegerField(verbose_name='wind speed')),
                ('humidity', models.PositiveSmallIntegerField(verbose_name='humidity')),
                ('soil_content', models.IntegerField(verbose_name='soil water content')),
                ('pressure', models.PositiveSmallIntegerField(verbose_name='air pressure')),
                ('temperature', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='temperature')),
                ('created', models.DateField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddConstraint(
            model_name='farm',
            constraint=models.UniqueConstraint(fields=('name', 'slug'), name='unique_name_slug'),
        ),
    ]
